package com.myorder.npr.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2019-05-23T10:52:07.919+02:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "Registration", 
                  wsdlLocation = "file:/Users/gayathrisivakumar/IdeaProjects/webservices/src/main/resources/thirdpartyrevoke.wsdl",
                  targetNamespace = "http://rdw.nl/rpv/1.0") 
public class Registration extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://rdw.nl/rpv/1.0", "Registration");
    public final static QName CustomBindingIRegistration = new QName("http://rdw.nl/rpv/1.0", "CustomBinding_IRegistration");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/gayathrisivakumar/IdeaProjects/webservices/src/main/resources/thirdpartyrevoke.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Registration.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/gayathrisivakumar/IdeaProjects/webservices/src/main/resources/thirdpartyrevoke.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Registration(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Registration(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Registration() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Registration(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Registration(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Registration(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IRegistration
     */
    @WebEndpoint(name = "CustomBinding_IRegistration")
    public IRegistration getCustomBindingIRegistration() {
        return super.getPort(CustomBindingIRegistration, IRegistration.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRegistration
     */
    @WebEndpoint(name = "CustomBinding_IRegistration")
    public IRegistration getCustomBindingIRegistration(WebServiceFeature... features) {
        return super.getPort(CustomBindingIRegistration, IRegistration.class, features);
    }

}
